# Generated by Django 6.0.4 on 2026-04-25 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_advertisement_celebrity_movietheater_movietv_news_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='anchor_url',
        ),
        migrations.AddField(
            model_name='slider',
            name='movie_genre_two',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='anchor_class',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='url',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='trailer',
            name='trailer_URL',
            field=models.CharField(max_length=200),
        ),
    ]
