# Generated by Django 6.0.4 on 2026-04-25 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_slider_anchor_url_slider_movie_genre_two_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='movie_genre_two',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
