# Generated by Django 6.0.4 on 2026-04-25 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_slider_movie_genre_two'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='img_src',
            field=models.CharField(max_length=50),
        ),
    ]
