# Generated by Django 6.0.4 on 2026-04-30 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_advertisement_img_src'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='section',
            field=models.CharField(default='sidebar', max_length=200),
            preserve_default=False,
        ),
    ]
